name: Java

on:
  push:
    branches: [ github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'

      - name: Build
        run: mvn --batch-mode -DskipTests package
        
      - name: Run tests with xvfb
        run: sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum mvn -B test --file pom.xml
        env:
          DISPLAY: :1
      - name: Tear down xvfb
        run: killall Xvfb
        
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: "**/test-results.trx"
          reporter: java-junit
          fail-on-error: true
