name: Java
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: corretto
      - name: Build
        run: mvn --batch-mode -DskipTests package
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -B test --file pom.xml
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
          
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: shanmupriyar57@gmail.com
          password: igumtaxgxckgfydy
          subject: Github Actions job result
          to: shanmupriya96@outlook.com
          from: Shanmugapriya Ravi
          body: Build job of To-Do-App-Tests completed successfully!
          cc: shanmupriya96@outlook.com
  
