name: To_Do_App_Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: corretto
          
      - name: Build
        id: build
        run: mvn --batch-mode -DskipTests package
        
      - name: Run headless test
        id: test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -B test --file pom.xml

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          
      - name: Report
        id: testreports
        uses: phoenix-actions/test-reporting@v10
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
      
      - name: Read output variables
        run: echo "url is ${{ steps.testreports.outputs.runHtmlUrl }}"
      
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: shanmupriyar57@gmail.com
          password: ${{secrets.PASSWORD}}
          subject: ${{ github.job }} job of ${{ github.repository }} Result
          to: shanmupriya96@outlook.com
          cc: shanmupriya96@outlook.com
          from: Shanmugapriya Ravi
          body: 
            ${{ github.job.build }} The Build in worflow ${{ github.workflow }} of ${{ github.repository }} Results 
    
            Build - ${{ steps.build.conclusion }} 
            
            Test - ${{ steps.test.conclusion }} 
            
            Passed - ${{ steps.testreports.outputs.passed }}
            
            Failed - ${{ steps.testreports.outputs.failed }}
            
            Skipped - ${{ steps.testreports.outputs.skipped }}
            
            Time - ${{ steps.testreports.outputs.time }}ms
            
            Click on the following link for a more detailed Test Report - ${{ steps.testreports.outputs.runHtmlUrl }}
        
            


